name = "vulazon/boattweentyped"
version = "1.1.1"
license = "MIT"
authors = ["boatbeaker"]
repository = "https://github.com/vulazon/BoatTween-Typed"
private=false

includes = [
  "pesde.toml",
  "LICENSE",
  "README.md",
  "src/**/*.luau",
]

[indices]
default = "https://github.com/pesde-pkg/index"

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]
